### PR TITLE
Close Issue #11

### LINKED ISSUE #11: Enhancement: Disabling HMD Mode when not in VR Mode
While AFrame is primarily a VR framework, I find the declarative nature of AFrame in building Three.js scenes much more readable and maintainable.  For that reason, I suggest that this library does not assume the Leap Motion is being used as part of an HMD. 

I have, as an experiment, already created listeners for the scene that will change the transform to HMD when put in VR mode.  However, it may be more desirable to have the HMD mode to exist independent of the mode in which AFrame is operating. 

Either way, let me know if you think this is a feature worth considering.

### PR DESCRIPTION
**Pull request by james-h-stephens**
To close [issue #11 ](https://github.com/openleap/aframe-leap-hands/issues/11)

Added leap-configuration component for configuring various features of the Leap Motion.

Added method to leap-system, which allows for the configuration of the setOptimizeHMD on the Leap Motion Controller.

Updated index.js to load the leap-configuration component.

### CODE REVIEW

**Comment by donmccurdy** [comment]
Sorry for the delay. I had hoped this would be a very simple change (see #14, not working), because systems can actually have schema just like components. Going to try to figure out why that simpler approach isn't working as expected and will follow up.

**Comment by james-h-stephens** [comment]
I had attempted your suggested method myself and found that the HMD property of the leap system schema was not being deserialized. I wasn't sure if it was a symptom of my unfamiliarity with AFrame. 

If you're experiencing the same, perhaps it's a bug in the framework.

**Comment by james-h-stephens** [comment]
I had attempted your suggested method myself and found that the HMD property of the leap system schema was not being deserialized. I wasn't sure if it was a symptom of my unfamiliarity with AFrame. 

If you're experiencing the same, perhaps it's a bug in the framework.

**Comment by donmccurdy** [comment]
Hi @james-h-stephens — thanks for your help looking into this. I've merged another commit (760dd8e9f6756646920f012f1cb59c7b8611ee61) that should resolve both issues. The original problems with my approach were a combination of a silly mistake on my part, and some unexpected API design choices in the LeapJS library.

Anyway, you should now be able to disable VR mode:

``` html
<a-scene leap="vr: false">
  <!-- ... -->
</a-scene>
```

By default, the hands will be around 0,0,0, so you may want to use an offset to move them in front of the camera a bit more:

``` html
<a-scene leap="vr: false; position: 0 0 -0.5;">
  <!-- ... -->
</a-scene>
```

Four new options are exposed: `vr`, `position`, `quaternion`, and `scale`. I decided against automatically changing settings when entering/leaving VR mode, but this could easily be done by an external component similar to the `leap-configuration` you've put together here.

Cheers

**Pull request closed without merging**
